services:
  - type: web
    name: fitcard
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: INSURANCE_SERVICE_URL
        sync: false
      - key: MSG91_AUTH_KEY
        sync: false
      - key: MSG91_SMS_TEMPLATE_ID
        sync: false
      - key: MSG91_EMAIL_TEMPLATE_ID
        sync: false
